### ISSUE TITLE
Cameras and Settings Feedback

### ISSUE THREAD

**Issue by Parthon** [ManticoreGamesInc/platform-documentation#1025]
The code for override camera:

local CAMERA = script:GetCustomProperty("Camera"):WaitForObject()
local localPlayer = Game.GetLocalPlayer()

localPlayer:SetOverrideCamera(propCamera)

Is incorrect, it should be propCamera on line 1, or CAMERA on line 4.

**Comment by CommanderFoo** [comment]
Thanks :)
