### ISSUE TITLE
Creat a rpg game 

### ISSUE THREAD

**Issue by jaxens** [ManticoreGamesInc/platform-documentation#1125]
dungeon crawler framework is not a frame work for rpg its more down the line of the frame work for a simlator game  with the customs and gear buy pads  not sure were this framework would be call rpg after playing around with this framework for a month  i found it had many bugs one being the framework is outdated  and would have to update  if i listen to the warnings but i did try to update the lines i keep getting warnings for and  ended up with over 256 errors so deleted the project and restarted a new one  watched all 4 videos on this framework found them not useful at all if i was to keep following the  videos  i would just be making a simlator  witch is not what i am wanting to make  plus  many times i had to make sure  i had a copy of the project i was working on the some assets in the  content that causes  the npc   that have projectiles to not work not sure what was the problem because checking the code   both on docs and tuts it was right so not sure what was the problem there  so i find my self hopeing combo loot mmo has the framework i looking for to start out with to making a rpg game sense most mmo are rpg games  that are online  and sense it has a updated ver of npc to use that mite not break so easy this time finger crossed

**Comment by StanzillaManticore** [comment]
Thanks for the feedback! You can find the code for LootMMO here https://github.com/standardcombo/LootMMO/
