### ISSUE TITLE
Call to Action: Coming from other Platforms

### ISSUE THREAD

**Issue by StanzillaManticore** [ManticoreGamesInc/platform-documentation#121]
We currently have a [Coming from other Platforms](https://github.com/ManticoreGamesInc/platform-documentation/blob/development/src/getting_started/other_platforms.md) document that is targeted at people new to Core **but** familiar with other game creators or engines, offering an overview over the common things differences. 

We are now posting this Call to Action to collect feedback on it, so please let us know what **your** most important "gotcha"'s were when you moved from a different tool to Core. 

What was the most important difference? What was really similar?

**Comment by richardkopelow** [comment]
When running, the Core Main Viewport acts like the Unity Game View and when paused it acts like the Scene View. When I started using Core I didn't even think to try pausing the game when I wanted to do Scene View stuff so pointing that out would be helpful.
