### ISSUE TITLE
How to side load

### ISSUE THREAD

**Issue by HS-CODES** [ManticoreGamesInc/platform-documentation#137]
Hello team, 
I downloaded the whole file but in a browser and then put it in Manticore- Core and it was verified too but it restarted the download amd my file 2.25 gb was changed to downloaded mb 92 mb , 

I checked log and found that there was something called force re download, i tried several time same happens . Plzz provide me a fix 

![IMG_20200402_172750](https://user-images.githubusercontent.com/58548448/78247033-c47d7a80-7507-11ea-9ae3-ed87a58e1e67.jpg)

Thanks

**Comment by StanzillaManticore** [comment]
Heya, please use our customer support for these kind of issues https://support.coregames.com/hc/en-us
