### ISSUE TITLE
Wrong parameter name in CoreLuaAPI.json

### ISSUE THREAD

**Issue by kerwanp** [ManticoreGamesInc/platform-documentation#681]
I am the developer of https://github.com/kerwanp/core-types-generator and found while generating the definition file that the name of a function parameter is not written in camel case and contains a space.

https://github.com/ManticoreGamesInc/platform-documentation/blob/6b91184f0fe14b8467ee127ba00f8a66287fa25a/src/assets/api/CoreLuaAPI.json#L5610

I've added a fix on core-types-generator to ensure that all parameter names are camel case, but you should also do it on your side.

**Comment by StanzillaManticore** [comment]
Thanks for noticing!
