### ISSUE TITLE
Vehicle Feedback

### ISSUE THREAD

**Issue by phantom567459** [ManticoreGamesInc/platform-documentation#718]
https://docs.coregames.com/api/vehicle/
`Off road sections are an excellent to encourage players to stay on the track.`
should be something like
`Off road sections are an excellent way to encourage players to stay on the track.`

Also in that paragraph:
`Once the vehicles exits the trigger the vehicle will drive at its original speed`
should be something like
`Once a vehicle exits the trigger, it will drive at its original speed`

**Comment by StanzillaManticore** [comment]
Awesome, thank you!
