### ISSUE TITLE
Race Timer Feedback

### ISSUE THREAD

**Issue by seaseaseaseaseaseasea** [ManticoreGamesInc/platform-documentation#772]
In https://docs.coregames.com/tutorials/race_timer/#move-player-to-starting-line

in the ipairs() info: 

> The order that elements are returned is guaranteed to be in the order of the indices, **and keys are are not an integer will be skipped.**

No idea what that means.

**Comment by CommanderFoo** [comment]
Hi,

I see there is a typo in there, but the explanation is correct. This is an advanced scripting tutorial, so it is assumed that the user has basic Lua knowledge, which would include understanding `ipairs`.

Basically what it means, is that if you added a key that isn't an integer, and looped over the array using `ipairs`, then that element you added would not get printed out, `ipairs` would skip over it.

Thanks
