### ISSUE TITLE
IK and Custom Animations Feedback

### ISSUE THREAD

**Issue by cranavis** [ManticoreGamesInc/platform-documentation#884]
Please add the real name we must use to get or set each anchor type in script.
RightHand ? Right_Hand ? right_hand ? rightHand ?
I will find alone, but it will be better if that is write in page.
have a nice day

Same for get Anchor Type.
Need exemple script.

**Comment by CommanderFoo** [comment]
IK Anchors can be attached to any bone (socket). It depends on your animation. This is why it doesn't specifically say what it needs to be attached too. This makes it much more flexible.

See the sockets here: https://docs.coregames.com/api/animations/#sockets

The anchor type is a property of the IK Anchor, so you can use the `IKAnchorType` Enum to see what type of anchor it is. 

https://docs.coregames.com/api/enums/#ikanchortype

**Comment by cranavis** [comment]
Hello.
The probleme were names not easy to find.
But it's done.

On any socket ? Not only on hands, pelvis and feet ?
Only 5 ar available in property list.

I hope devs will unlock anchors for animated meshes.

Have a nice day.


De : Peter ***@***.***>
À : ManticoreGamesInc/platform-documentation ***@***.***>
Sujet : Re: [ManticoreGamesInc/platform-documentation] IK and Custom Animations Feedback (Issue #884)
Date : 03/01/2022 19:59:43 Europe/Paris
Copie à : cranavis ***@***.***>;
   Author ***@***.***>


IK Anchors can be attached to any bone (socket). It depends on your animation. This is why it doesn't specifically say what it needs to be attached too. This makes it much more flexible.

See the sockets here: https://docs.coregames.com/api/animations/#sockets

The anchor type is a property of the IK Anchor, so you can use the IKAnchorType Enum to see what type of anchor it is.

https://docs.coregames.com/api/enums/#ikanchortype

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
