### ISSUE TITLE
✨ Concurrent Storage Feedback

### ISSUE THREAD

**Issue by seaseaseaseaseaseasea** [ManticoreGamesInc/platform-documentation#887]
When you double-click on TotalPlayersServer, it will select "TotalPlayersServer ". It would be better if it selected "TotalPlayersServer" without the space at the end.

**Comment by CommanderFoo** [comment]
This is the default behaviour for browsers. Some browsers (i.e. Chrome) will allow you to remove the space. You have to double click on the word, keep the button held down, then move left a small amount. Not all browsers support this though unfortunately.

If you are using Firefox, then there is a config setting you can change.

Writing some JavaScript just to try and fix this issue could potentially cause other issues when messing with text ranges on the page, so going down that route is not a good idea.
